### ISSUE TITLE
SQLite-PCL plugin throws NullReferenceException when using Mvx.Resolve<IMvxSqliteConnectionFactory>()

### ISSUE THREAD

**Issue by ThomasLebrun** [MvvmCross/MvvmCross-Plugins#80]
### Steps to reproduce

I'm trying to use the SQLite-PCL plugin (version 4.1) in a Windows UWP app, using MvvmCross 4.1.
I've added the Bootstrap class:

`public class SqlitePluginBootstrap 
        : MvxPluginBootstrapAction<PluginLoader>
    {
    }`

But every time I tried to resolve the IMvxSqliteConnectionFactory, I get an NullReferenceException:

`public DatabaseManager()
        {
            _sqliteConnectionFactory = Mvx.Resolve<IMvxSqliteConnectionFactory>();
        }`

>    at MvvmCross.Platform.Mvx.Resolve[TService]()
>    at Citatio.Core.Domain.Data.DatabaseManager..ctor()
>    at Citatio.Core.Domain.Data.DatabaseManager.<>c.<.cctor>b__10_0()
>    at System.Lazy`1.CreateValue()
>    at System.Lazy`1.LazyInitValue()
>    at Citatio.Core.Domain.Data.DatabaseManager.get_Instance()
>    at Citatio.Windows.Client.Views.ExtendedSplash.<DismissedEventHandler>d__9.MoveNext()

Any ideas ?
### Configuration

**Version:** 4.1.0

**Platform:** Windows UWP

**Comment by ThomasLebrun** [comment]
Nevermind, stupid issue on my side, sorry for the inconvenience... :)
